videos:
  - name: Jordan peterson 1
    id: onimr6jKlvg
  - name: Jordan peterson 1
    id: 37wj0qrLykg
  - name: Jordan peterson 1
    id: R32S9765Vao
  - name: Jordan peterson 1
    id: YxwLMXG-lz8
  - name: Jordan peterson 1
    id: zQ1eQQvoy5g
  - name: Jordan peterson 1
    id: KZliwgcusYM
  - name: Jordan peterson 1
    id: Zjm36k2GoW0
  - name: Jordan peterson 1
    id: aMcjxSThD54
  - name: Jordan peterson 1
    id: aSdZgcjmLkY
  - name: Jordan peterson 1
    id: gQYCJIDHGnQ
  - name: Jordan peterson 1
    id: JX9B5tnj-xI
  - name: Jordan peterson 1
    id: QmBzn-veFiE
  - name: Jordan peterson 1
    id: lwhGAUJ9ouA
  - name: Jordan peterson 1
    id: 7_qojiXsycw
  - name: Jordan peterson 1
    id: xnpUFLD_xlw
  - name: Jordan peterson 1
    id: 0P2ghrAThT0
  - name: Jordan peterson 1
    id: rvfn1wMAFgU
  - name: Jordan peterson 1
    id: 5Aoy08tjHlg
